spring:
  application:
    name: form-data-storage-migration-cli
  main:
    web-application-type: none
    banner-mode: off
    log-startup-info: off
    allow-bean-definition-overriding: true

additional-key-patterns: